
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL DOISPONTOS LCHAVETA LPR NULL NUM RCHAVETA RPR STRING VIRG\n    object : LCHAVETA members RCHAVETA\n    \n    members : par\n            | par VIRG members\n    \n    par : STRING DOISPONTOS value\n    \n    array : LPR elementos RPR\n    \n    elementos : value\n             | value VIRG elementos\n    \n    value : object\n          | NULL\n          | array\n    \n    value : BOOL\n    \n    value : NUM\n    \n    value : STRING\n    '
    
_lr_action_items = {'LCHAVETA':([0,8,17,21,],[2,2,2,2,]),'$end':([1,6,],[0,-1,]),'STRING':([2,7,8,17,21,],[5,5,10,10,10,]),'RCHAVETA':([3,4,6,9,10,11,12,13,14,15,16,20,],[6,-2,-1,-3,-13,-4,-8,-9,-10,-11,-12,-5,]),'VIRG':([4,6,10,11,12,13,14,15,16,19,20,],[7,-1,-13,-4,-8,-9,-10,-11,-12,21,-5,]),'DOISPONTOS':([5,],[8,]),'RPR':([6,10,12,13,14,15,16,18,19,20,22,],[-1,-13,-8,-9,-10,-11,-12,20,-6,-5,-7,]),'NULL':([8,17,21,],[13,13,13,]),'BOOL':([8,17,21,],[15,15,15,]),'NUM':([8,17,21,],[16,16,16,]),'LPR':([8,17,21,],[17,17,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object':([0,8,17,21,],[1,12,12,12,]),'members':([2,7,],[3,9,]),'par':([2,7,],[4,4,]),'value':([8,17,21,],[11,19,19,]),'array':([8,17,21,],[14,14,14,]),'elementos':([17,21,],[18,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> object","S'",1,None,None,None),
  ('object -> LCHAVETA members RCHAVETA','object',3,'p_object','jsonToToml.py',47),
  ('members -> par','members',1,'p_members','jsonToToml.py',53),
  ('members -> par VIRG members','members',3,'p_members','jsonToToml.py',54),
  ('par -> STRING DOISPONTOS value','par',3,'p_par','jsonToToml.py',63),
  ('array -> LPR elementos RPR','array',3,'p_array','jsonToToml.py',69),
  ('elementos -> value','elementos',1,'p_elementos','jsonToToml.py',76),
  ('elementos -> value VIRG elementos','elementos',3,'p_elementos','jsonToToml.py',77),
  ('value -> object','value',1,'p_value_outros','jsonToToml.py',86),
  ('value -> NULL','value',1,'p_value_outros','jsonToToml.py',87),
  ('value -> array','value',1,'p_value_outros','jsonToToml.py',88),
  ('value -> BOOL','value',1,'p_value_Bool','jsonToToml.py',96),
  ('value -> NUM','value',1,'p_value_NUM','jsonToToml.py',102),
  ('value -> STRING','value',1,'p_value_String','jsonToToml.py',114),
]
